In [22]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

#Muda a fonte dos Plots para Arial
plt.rcParams["font.family"] = "Arial"
plt.rcParams["mathtext.fontset"] = "custom"
plt.rcParams['mathtext.rm'] = "Arial"
plt.rcParams['mathtext.it'] = "Arial:italic"
plt.rcParams['mathtext.bf'] = "Arial:bold"
plt.rcParams['figure.figsize'] = (8, 4)

In [23]:
class KNNClassificador:    
    # Definição da Classe
    def __init__(self, k=3):
        self.k = k
        self.X_treino = None
        self.y_treino = None

    # Função de Treinamento
    def fit(self, X, y):
        self.X_treino = np.array(X)
        self.y_treino = np.array(y)
        return self

    # Função para calcular a distância (euclidiana)
    def _calcular_distancia(self, a, b):
        return np.sqrt(np.sum((a - b)**2))

    # Função para prever um valor
    def _prever_um(self, x):
        # Calcular as distâncias do ponto x até todos os pontos de treinamento
        distancias = np.array([
            self._calcular_distancia(x, x_treino)
            for x_treino in self.X_treino
        ])
        # Dizer quais indices correspondem as menores distâncias
        indices_vizinhos = np.argsort(distancias)[:self.k]
        # Identificar a quais classes pertecem essas menores distâncias
        classes_vizinhos = self.y_treino[indices_vizinhos]
        # Elencar quais classes aparecem nas menores distâncias
        classes_unicas = np.unique(self.y_treino)
        # Criar um dicionário, em que para cada entrada tenho a classe e o valor 
        # é a quantidade de fezes em que a classe aparece na classe_vizinhos
        votos = {c: np.sum(classes_vizinhos == c) for c in classes_unicas}
        # Retorna a classe com maior valor
        return max(votos, key=votos.get)

    # Função para prever uma grande quantidade de valores
    def predict(self, X):
        X = np.array(X)
        return np.array([self._prever_um(x) for x in X])

In [24]:
iris = load_iris()
X, y = iris.data, iris.target

df = pd.DataFrame(X, columns=iris.feature_names)
df['target'] = y
df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0


In [31]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [34]:
print(f"#setosa = {np.bincount(y)[0]}")
print(f"#versicolor = {np.bincount(y)[1]}")
print(f"#virginica = {np.bincount(y)[2]}")

#setosa = 50
#versicolor = 50
#virginica = 50


In [25]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

print(f"Treino: {X_train.shape[0]} amostras")
print(f"Teste:  {X_test.shape[0]} amostras")

Treino: 105 amostras
Teste:  45 amostras


In [26]:
scaler = StandardScaler()
X_train_sc = scaler.fit_transform(X_train)
X_test_sc  = scaler.transform(X_test)      #Nao é necessario o fit_transform pois a media e a variancia
                                           #ja foram calculados

In [27]:
meu_knn = KNNClassificador(k=5)
meu_knn.fit(X_train, y_train)

In [28]:
y_prev = meu_knn.predict(X_test)
print(confusion_matrix(y_prev, y_test))

[[15  0  0]
 [ 0 15  1]
 [ 0  0 14]]
